/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tutorial_HelloWorldJNI */

#ifndef _Included_com_tutorial_HelloWorldJNI
#define _Included_com_tutorial_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tutorial_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tutorial_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_tutorial_HelloWorldJNI
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_tutorial_HelloWorldJNI_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tutorial_HelloWorldJNI
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tutorial_HelloWorldJNI_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_tutorial_HelloWorldJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lcom/tutorial/UserData;
 */
JNIEXPORT jobject JNICALL Java_com_tutorial_HelloWorldJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_tutorial_HelloWorldJNI
 * Method:    printUserData
 * Signature: (Lcom/tutorial/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tutorial_HelloWorldJNI_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
